//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolonterWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqiesrUser
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> RequestId { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
